apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterresourceoverrides.operator.autoscaling.openshift.io
spec:
  group: operator.autoscaling.openshift.io
  scope: Cluster
  names:
    plural: clusterresourceoverrides
    singular: clusterresourceoverride
    kind: ClusterResourceOverride
    listKind: ClusterResourceOverrideList
    shortNames:
      - cro
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                podResourceOverride:
                  type: object
                  properties:
                    spec:
                      type: object
                      properties:
                        memoryRequestToLimitPercent:
                          type: integer
                          minimum: 1
                          maximum: 100
                        cpuRequestToLimitPercent:
                          type: integer
                          minimum: 1
                          maximum: 100
                        limitCPUToMemoryPercent:
                          type: integer
                          minimum: 0
            status:
              type: object
              description: The status of the ClusterResourceOverride
